### ISSUE TITLE
CI Failing due to an Incompatible Seed on Synapse

### ISSUE THREAD

**Issue by alittlesliceoftom** [dbt-msft/tsql-utils#13]
The CI is failing during the dbt seed stage due to an ill formatted file (for synapse), the file is formatted fine for the Azure SQL runs. 

![image](https://user-images.githubusercontent.com/11210917/102697057-a1782f80-422a-11eb-8d83-40b70e05d29a.png)

This means that the tests aren't running for synapse

The data is not stored in this repo, but in dbt_utils (https://github.com/fishtown-analytics/dbt-utils/blob/master/integration_tests/data/etc/data_people.csv)

A local fix could  be to let dbt seed fail gracefully without raising an error to the CI and preventing the test from running. Or to identify why this file does not work and fixing that. Alternately we could --exclude the file's load, but we would also have to then exclude downstream tests which quickly gets messy.

**Comment by swanderz** [comment]
Check out https://github.com/dbt-msft/dbt-synapse/issues/30 I think we almost have a fix

**Comment by swanderz** [comment]
this issue is fixed now but I still have to cut a new official release and push it to PyPI
