### ISSUE TITLE
communicte what macros are not supported by tsql-utils

### ISSUE THREAD

**Issue by dataders** [dbt-msft/tsql-utils#19]
currently the only place where you can see what models are not supported is by looking at `integration_tests/dbt_utils/dbt_project.yml` (see below) which is not intuitive, but while the YAML is precise the models and tests in the integration tests don't necessarily correspond 1-1 with individual macros.

Maybe something in the `README.md`? Or perhaps just one issue per macro? However, `dbt_utils.group_by()` I know we'll never support. worth mentioning?

### currently unsupported
after https://github.com/dbt-msft/tsql-utils/pull/17 the current macros we still could port are:
`test_split_part()` (not working on Synapse?)
`test_date_spine()`
`insert_by_period` materialization
`generate_series()`
`get_column_values()`
`get_relations_by_pattern()`
`get_relations_by_prefix_and_union()`
`get_url_host()`
`get_url_parameter()`
`get_url_path()`

https://github.com/dbt-msft/tsql-utils/blob/b68b3a9d8871fd0963a7f36cf455c29b81be9341/integration_tests/dbt_utils/dbt_project.yml#L22-L62

**Comment by alittlesliceoftom** [comment]
Above is (I think) the list of macros which are integration tested on dbt_utils, but don't yet work here. 

There are also interesting legacy macros that are a bit behind on dbt_utils too, and not fully tested, but represent useful and interesting concepts. For instance - https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/materializations/insert_by_period_materialization.sql the insert by period materialisation here is a useful idea - especially for SQL Server, but doesn't work on a first test in my local and looks like it could generally do with a spruce.

**Comment by swanderz** [comment]
perhaps for all the unsupported macros, we could implement `sqlserver__*` versions as wrappers for `UnsupportedException`s. @jtcohen6 I remember seeing an example of this somewhere but can't remember now...

**Comment by jtcohen6** [comment]
Many of the required adapter macros raise an exception in the default implementation, e.g. [`list_relations_without_caching`](https://github.com/fishtown-analytics/dbt/blob/36d1bddc5b3ec7b0f503972d7138e8260693da38/core/dbt/include/global_project/macros/adapters/common.sql#L235-L243).

**Comment by sdebruyn** [comment]
Nobody is maintaining it in this level of detail and the parent packages also update from time to time. Best to have issues for the things which don't work.
