### ISSUE TITLE
Add testing models for the macros

### ISSUE THREAD

**Issue by alittlesliceoftom** [dbt-msft/tsql-utils#3]
I can open a PR for this with samples from dbt-utils.

Options: 
1. We provide project that installs dbt-utils and tsql-utils in correct way, then runs the tests from dbt-utils. This may be implemented by the integration-tests code I can see floating around, but this seems to mostly be config? 
2. We copy appropriate tests into this repo.

**Comment by swanderz** [comment]
you've read my mind: see #4

**Comment by sdebruyn** [comment]
testing is implemented
