### ISSUE TITLE
Hub page top installation should be changed

### ISSUE THREAD

**Issue by NicolasPA** [dbt-msft/tsql-utils#65]
https://hub.getdbt.com/dbt-msft/tsql_utils/latest/

The top of the hub page contains a default package installation configuration that is insufficient as described by the  README instructions https://github.com/dbt-msft/tsql-utils#installation-instructions.

To reduce confusion for newcomers, I suggest modifying this Hub page so the top "Installation" part equals the README instruction.

**Comment by sdebruyn** [comment]
Out of our control, this is for https://github.com/dbt-labs/hub.getdbt.com
