### ISSUE TITLE
`dbt_utils.hash` failing for synapse

### ISSUE THREAD

**Issue by dataders** [dbt-msft/tsql-utils#69]
I don't think this is an error with the macro, but really something weird going on with equivalence. for example, why aren't the below equal in Synapse?

| actual                           | expected                         |
|----------------------------------|----------------------------------|
| D41D8CD98F00B204E9800998ECF8427E | d41d8cd98f00b204e9800998ecf8427e |

**Comment by alittlesliceoftom** [comment]
@swanderz , what's the generative code for the 2 columns above ?  Or what made you realise there was a problem?

**Comment by sdebruyn** [comment]
Not part of this repo anymore, fixed in the adapter
