### ISSUE TITLE
Warning: the `concat` macro is now provided in dbt Core with dbt_core 1.3.0+

### ISSUE THREAD

**Issue by hernanparra** [dbt-msft/tsql-utils#89]
I'm using the tsql_utils.surrogate_key macro and when running or compiling dbt I get this warning:
Warning: the `concat` macro is now provided in dbt Core. It is no longer available in dbt_utils and backwards compatibility will be removed in a future version of the package. Use `concat` (no prefix) instead.

**Comment by ndam90** [comment]
I has a similar issue when using the tsql_utils.surrogate_key with warning:
'dict object' has no attribute 'concat'
I found that in the upgrade to dbt_utils version 1.0 they moved cross-db macros to the dbt namespace, with no changes necessary other than replacing dbt_utils. with dbt.
When replacing the namespace dbt_utils. to dbt. inside the tsql_utils.surrogate_key script for both **concat** and **hash** it worked perfectly.

I see there is a pull request for this issue already.

**Comment by sdebruyn** [comment]
should be fixed now
